services:
  producer:
    container_name: producer
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      AMQP_URL: 'amqp://root:password@rabbitmq:5672?connection_attempts=5&retry_delay=5'
    volumes:
      - ./:/app:delegated
    working_dir: /app/producer
    command:
      - go
      - run
      - main.go
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      AMQP_URL: 'amqp://root:password@rabbitmq:5672?connection_attempts=5&retry_delay=5'
    volumes:
      - ./:/app:delegated
    working_dir: /app/consumer
    command:
      - go
      - run
      - main.go
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.12-management
    ports:
      # The standard AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
